#!/usr/bin/env bash


set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)"
REPO_ROOT="$(cd -- "${SCRIPT_DIR}/.." &>/dev/null && pwd)"

RUN_ID="${MILES_RUN_ID:-glm47_h100_pie_cpp_lora_r16_$(date +%Y%m%d_%H%M%S)}"
export MILES_RUN_ID="${RUN_ID}"
export MILES_RUN_ROOT="${MILES_RUN_ROOT:-${REPO_ROOT}/.glm47-posttraining/miles/glm47-h100-cpp-perf/runs/${RUN_ID}}"
export MILES_MODEL_ARGS_FILE="${MILES_MODEL_ARGS_FILE:-glm4.7-flash.sh}"
export MILES_HF_CHECKPOINT="${MILES_HF_CHECKPOINT:-/root/models/GLM-4.7-Flash}"
export MILES_REF_LOAD_DIR="${MILES_REF_LOAD_DIR:-${MILES_HF_CHECKPOINT}_torch_dist_tp4_pp1_ep8}"

export MILES_GPUS_PER_NODE="${MILES_GPUS_PER_NODE:-8}"
export MILES_TENSOR_MODEL_PARALLEL_SIZE="${MILES_TENSOR_MODEL_PARALLEL_SIZE:-4}"
export MILES_PIPELINE_MODEL_PARALLEL_SIZE="${MILES_PIPELINE_MODEL_PARALLEL_SIZE:-1}"
export MILES_CONTEXT_PARALLEL_SIZE="${MILES_CONTEXT_PARALLEL_SIZE:-1}"
export MILES_EXPERT_MODEL_PARALLEL_SIZE="${MILES_EXPERT_MODEL_PARALLEL_SIZE:-8}"
export MILES_EXPERT_TENSOR_PARALLEL_SIZE="${MILES_EXPERT_TENSOR_PARALLEL_SIZE:-1}"
export MILES_SEQ_LENGTH="${MILES_SEQ_LENGTH:-4096}"

export MILES_MAX_TOKENS_PER_GPU="${MILES_MAX_TOKENS_PER_GPU:-16384}"
export MILES_MICRO_BATCH_SIZE="${MILES_MICRO_BATCH_SIZE:-1}"
export MILES_RECOMPUTE_GRANULARITY="${MILES_RECOMPUTE_GRANULARITY:-selective}"
export MILES_USE_DYNAMIC_BATCH_SIZE="${MILES_USE_DYNAMIC_BATCH_SIZE:-1}"
export MILES_BALANCE_DATA="${MILES_BALANCE_DATA:-1}"

export MILES_MOE_TOKEN_DISPATCHER_TYPE="${MILES_MOE_TOKEN_DISPATCHER_TYPE:-flex}"
export MILES_MOE_ENABLE_DEEPEP="${MILES_MOE_ENABLE_DEEPEP:-1}"
export NVSHMEM_DISABLE_NCCL="${NVSHMEM_DISABLE_NCCL:-1}"
export MILES_ATTENTION_BACKEND="${MILES_ATTENTION_BACKEND:-flash}"


export MILES_NUM_ROLLOUT="${MILES_NUM_ROLLOUT:-100}"
export MILES_ROLLOUT_BATCH_SIZE="${MILES_ROLLOUT_BATCH_SIZE:-32}"
export MILES_N_SAMPLES_PER_PROMPT="${MILES_N_SAMPLES_PER_PROMPT:-8}"
export MILES_GLOBAL_BATCH_SIZE="${MILES_GLOBAL_BATCH_SIZE:-256}"
export MILES_ROLLOUT_MAX_RESPONSE_LEN="${MILES_ROLLOUT_MAX_RESPONSE_LEN:-1536}"
export MILES_ROLLOUT_TEMPERATURE="${MILES_ROLLOUT_TEMPERATURE:-1.0}"
export MILES_EVAL_MAX_RESPONSE_LEN="${MILES_EVAL_MAX_RESPONSE_LEN:-1536}"
export MILES_EVAL_N_SAMPLES_PER_PROMPT="${MILES_EVAL_N_SAMPLES_PER_PROMPT:-1}"
export MILES_EVAL_INTERVAL="${MILES_EVAL_INTERVAL:-20}"
export MILES_SAVE_INTERVAL="${MILES_SAVE_INTERVAL:-10}"
export MILES_LR="${MILES_LR:-2e-6}"
export MILES_NO_REF="${MILES_NO_REF:-1}"


export MILES_SGLANG_MEM_FRACTION_STATIC="${MILES_SGLANG_MEM_FRACTION_STATIC:-0.75}"
export MILES_SGLANG_SERVER_CONCURRENCY="${MILES_SGLANG_SERVER_CONCURRENCY:-1024}"
export MILES_SGLANG_CUDA_GRAPH_MAX_BS="${MILES_SGLANG_CUDA_GRAPH_MAX_BS:-64}"
export MILES_SGLANG_MAX_RUNNING_REQUESTS="${MILES_SGLANG_MAX_RUNNING_REQUESTS:-256}"
export MILES_SGLANG_ENABLE_DP_ATTENTION="${MILES_SGLANG_ENABLE_DP_ATTENTION:-1}"
export MILES_SGLANG_DP_SIZE="${MILES_SGLANG_DP_SIZE:-8}"
export MILES_SGLANG_ENABLE_DP_LM_HEAD="${MILES_SGLANG_ENABLE_DP_LM_HEAD:-1}"
export MILES_SGLANG_MOE_DENSE_TP_SIZE="${MILES_SGLANG_MOE_DENSE_TP_SIZE:-1}"

export MILES_SGLANG_SPECULATIVE="${MILES_SGLANG_SPECULATIVE:-0}"
export MILES_SGLANG_SPECULATIVE_NUM_STEPS="${MILES_SGLANG_SPECULATIVE_NUM_STEPS:-3}"
export MILES_SGLANG_SPECULATIVE_EAGLE_TOPK="${MILES_SGLANG_SPECULATIVE_EAGLE_TOPK:-1}"
export MILES_SGLANG_SPECULATIVE_NUM_DRAFT_TOKENS="${MILES_SGLANG_SPECULATIVE_NUM_DRAFT_TOKENS:-4}"
export MILES_SGLANG_DISABLE_CUSTOM_ALL_REDUCE="${MILES_SGLANG_DISABLE_CUSTOM_ALL_REDUCE:-0}"

export MILES_SGLANG_ATTENTION_BACKEND="${MILES_SGLANG_ATTENTION_BACKEND:-flashinfer}"

export MILES_LORA_TARGET_MODULES="${MILES_LORA_TARGET_MODULES:-q_a_proj,kv_a_proj_with_mqa,o_proj,gate_proj,up_proj,down_proj}"
export MILES_SGLANG_LORA_TARGET_MODULES="${MILES_SGLANG_LORA_TARGET_MODULES:-${MILES_LORA_TARGET_MODULES}}"
export MILES_EXPERTS_SHARED_OUTER_LORAS="${MILES_EXPERTS_SHARED_OUTER_LORAS:-1}"
export MILES_LORA_BASE_CPU_BACKUP="${MILES_LORA_BASE_CPU_BACKUP:-1}"
export MILES_NO_GRADIENT_ACCUMULATION_FUSION="${MILES_NO_GRADIENT_ACCUMULATION_FUSION:-1}"
export MILES_SGLANG_LORA_USE_VIRTUAL_EXPERTS="${MILES_SGLANG_LORA_USE_VIRTUAL_EXPERTS:-1}"



_default_chat_template_kwargs='{"enable_thinking": false}'
export MILES_APPLY_CHAT_TEMPLATE_KWARGS="${MILES_APPLY_CHAT_TEMPLATE_KWARGS:-${_default_chat_template_kwargs}}"
export MILES_TRAIN_MODULE="${MILES_TRAIN_MODULE:-glm47_posttraining.integrations.miles_train_with_glm47_bridge}"
export GLM47_REGISTER_BRIDGE="${GLM47_REGISTER_BRIDGE:-1}"


export GLM47_CPP_REWARD_WORKERS="${GLM47_CPP_REWARD_WORKERS:-32}"
export GLM47_CPP_SANDBOX_CPU="${GLM47_CPP_SANDBOX_CPU:-1}"
export GLM47_CPP_SANDBOX_BACKEND="${GLM47_CPP_SANDBOX_BACKEND:-local}"

export GLM47_EXPERIMENT_ID="${GLM47_EXPERIMENT_ID:-${RUN_ID}}"
export MILES_WANDB_PROJECT="${MILES_WANDB_PROJECT:-glm47-pie-cpp-posttraining}"
export MILES_WANDB_GROUP="${MILES_WANDB_GROUP:-${GLM47_EXPERIMENT_ID}}"
export MILES_WANDB_RUN_ID="${MILES_WANDB_RUN_ID:-${RUN_ID}}"
export MILES_WANDB_JOB_TYPE="${MILES_WANDB_JOB_TYPE:-grpo}"
export WANDB_RUN_GROUP="${WANDB_RUN_GROUP:-${GLM47_EXPERIMENT_ID}}"
export WANDB_JOB_TYPE="${WANDB_JOB_TYPE:-grpo}"
export WANDB_TAGS="${WANDB_TAGS:-canonical,pie-cpp,grpo}"

if [ "${MILES_SKIP_RUNTIME_PREFLIGHT:-0}" != "1" ]; then
  "${MILES_PYTHON:-python3}" "${REPO_ROOT}/scripts/check_runtime.py"
fi

if [ -n "${MILES_LORA_ADAPTER_PATH:-}" ] && [ "${MILES_AUTO_PREPARE_GRPO_ADAPTER:-1}" = "1" ]; then
  TRAINER_ADAPTER_PATH="${MILES_LORA_ADAPTER_PATH}"
  HYBRID_ADAPTER_PATH="${MILES_GRPO_ADAPTER_DIR:-${MILES_RUN_ROOT}/adapter_hybrid}"
  export MILES_LORA_SOURCE_ADAPTER_PATH="${TRAINER_ADAPTER_PATH}"



  PREPARE_ARGS=(
    --include-native
    --expected-native-shards "${MILES_EXPECTED_SOURCE_NATIVE_SHARDS:-${MILES_EXPECTED_NATIVE_SHARDS:-${MILES_TENSOR_MODEL_PARALLEL_SIZE}}}"
  )
  if [ -n "${MILES_EXPECTED_SOURCE_ADAPTER_SHA256:-}" ]; then
    PREPARE_ARGS+=(--expected-source-sha256 "${MILES_EXPECTED_SOURCE_ADAPTER_SHA256}")
  fi
  if [ -n "${MILES_EXPECTED_SOURCE_TENSORS:-}" ]; then
    PREPARE_ARGS+=(--expected-source-tensors "${MILES_EXPECTED_SOURCE_TENSORS}")
  fi
  if [ -n "${MILES_EXPECTED_STRIPPED_TENSORS:-}" ]; then
    PREPARE_ARGS+=(--expected-stripped-tensors "${MILES_EXPECTED_STRIPPED_TENSORS}")
  fi
  "${MILES_PYTHON:-python3}" "${REPO_ROOT}/scripts/prepare_grpo_adapter.py" \
    "${PREPARE_ARGS[@]}" "${TRAINER_ADAPTER_PATH}" "${HYBRID_ADAPTER_PATH}"
  export MILES_LORA_ADAPTER_PATH="${HYBRID_ADAPTER_PATH}"
fi

exec "${REPO_ROOT}/scripts/train_grpo.sh" "$@"
